### ISSUE TITLE
Eth-netstat GUI is showing "offline" status for local node (which is running)

### ISSUE THREAD

**Issue by bhupendraji** [cubedro/eth-netstats#293]
I am running eth test RPC on MAc with a default 8545 port. I followed all the instructions for installing eth-netstats, however the node is showing offline. Is there anything I am missing

**Comment by hello2mao** [comment]
same problem, any update?

**Comment by AyushyaChitransh** [comment]
Nodes being displayed on the site are made available via APIs. Make sure the API from https://github.com/cubedro/eth-net-intelligence-api is running.

**Comment by hello2mao** [comment]
```
09:21:02 3|node-4   | 2018-08-02 09:21 +00:00: [his] =s= Got history request
09:21:02 3|node-4   | [his] =s= Getting history from undefined to undefined
09:21:02 3|node-4   | 2018-08-02 09:21 +00:00: [eth] =✘= TypeError: results.reverse is not a function
09:21:02 3|node-4   |     at /eth-net-intelligence-api/lib/node.js:622:21
09:21:02 3|node-4   |     at /eth-net-intelligence-api/node_modules/async/lib/async.js:52:16
09:21:02 3|node-4   |     at /eth-net-intelligence-api/node_modules/async/lib/async.js:361:13
09:21:02 3|node-4   |     at /eth-net-intelligence-api/node_modules/async/lib/async.js:52:16
09:21:02 3|node-4   |     at iterate (/eth-net-intelligence-api/node_modules/async/lib/async.js:260:24)
09:21:02 3|node-4   |     at async.forEachOfSeries.async.eachOfSeries (/eth-net-intelligence-api/node_modules/async/lib/async.js:281:9)
09:21:02 3|node-4   |     at _asyncMap (/eth-net-intelligence-api/node_modules/async/lib/async.js:355:9)
09:21:02 3|node-4   |     at Object.mapSeries (/eth-net-intelligence-api/node_modules/async/lib/async.js:347:20)
09:21:02 3|node-4   |     at Node.getHistory (/eth-net-intelligence-api/lib/node.js:601:8)
09:21:02 3|node-4   |     at Primus.<anonymous> (/eth-net-intelligence-api/lib/node.js:246:8)
2018-08-02 09:21:02: App [node-4] with id [3] and pid [2152], exited with code [1] via signal [SIGINT]
09:21:02 PM2        | App [node-4] with id [3] and pid [2152], exited with code [1] via signal [SIGINT]
2018-08-02 09:21:02: Starting execution sequence in -fork mode- for app name:node-4 id:3
09:21:02 PM2        | Starting execution sequence in -fork mode- for app name:node-4 id:3
```
```
async.mapSeries(interv, function (number, callback)
	{
		web3.eth.getBlock(number, false, callback);
	},
	function (err, results)
	{
		if (err) {
			console.error('his', 'history fetch failed:', err);

			results = false;
		}
		else
		{
			for(var i=0; i < results.length; i++)
			{
				results[i] = self.formatBlock(results[i]);
			}
		}

		self.emit('history', {
			id: self.id,
			history: results.reverse()
		});

		console.timeEnd('=H=', 'his', 'Got history in');
	});
```


results maybe not an array, there is a bug?

**Comment by hello2mao** [comment]
results maybe not an array,  there is a bug?

**Comment by hello2mao** [comment]
@cubedro hi，could you help me to fix it?

**Comment by zscole** [comment]
Is ETH Net Intelligence API running on the other nodes in the network? You need to indicate the URL of the node that's running ETH netstats and also the port number.
