### ISSUE TITLE
RangeError: out of range index

### ISSUE THREAD

**Issue by ethernomad** [cubedro/eth-netstats#296]
```
/root/eth-netstats/node_modules/ws/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (/root/eth-netstats/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/root/eth-netstats/node_modules/ws/lib/Receiver.js:86:3)
    at Socket.realHandler (/root/eth-netstats/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by aswinkumarrhex** [comment]
hi
E:\Projects\Eth_Monitor\eth-netstats-master\node_modules\ws\lib\Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (E:\Projects\Eth_Monitor\eth-netstats-master\node_modules\ws\lib
\Receiver.js:386:24)
    at Receiver.add (E:\Projects\Eth_Monitor\eth-netstats-master\node_modules\ws
\lib\Receiver.js:86:3)
    at Socket.realHandler (E:\Projects\Eth_Monitor\eth-netstats-master\node_modu
les\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.5.0
npm ERR! code ELIFECYCLE
npm ERR! npm  v3.10.3
npm ERR! eth-netstats@0.0.9 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eth-netstats@0.0.9 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eth-netstats package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eth-netstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls eth-netstats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projects\Eth_Monitor\eth-netstats-master\npm-debug.log


Not sure if i am doing this right but I see lots of versions listed inside my dir
Node Global is 6.5.0
ws global 1.1.1
web3 0.15.3

can someone help me understand the issue here ?
the application Executes but after a certain time period i get this error and application terminates !

**Comment by mattcrooks** [comment]
I was having the same issue and found [this issue](https://github.com/websockets/ws/issues/778) relating to one of the dependencies (websockets).

I have just upgraded `ws` to `1.1.1` as suggested. I'm still testing but it is looking promising.

> To upgrade run `npm install --save ws@latest` 

Hope this helps resolve your issue.
